### ISSUE TITLE
2013 Standards

### ISSUE THREAD

**Issue by ghost** [winfinit/aamvajs#1]
I'd first like to say THANK YOU! This is the first parser I've found on the web using javascript. I really appreciate the hard work.

If you ever feel the need to complete this, the new 2013 standard is out which would be really helpful.

**Comment by ghost** [comment]
It doesn't look like these new 2013 licenses are getting parsed at all. Please let me know if you'd be willing to update this library. I don't know of anyone else actually willing to do this.

**Comment by winfinit** [comment]
Hello,

yes, i would love to fix it, can you obfuscate raw stream, and send it to me by any means please?

thank you
Roman.

**Comment by ghost** [comment]
Thanks Roman! It's actually a 2012 model that isn't working. I sent you 2 examples to your email.

**Comment by winfinit** [comment]
Bryan,

just published 0.0.16, parser is now returning results for two samples that were sent, thank you for sharing them with me!
