### ISSUE TITLE
Would you consider a dual license.

### ISSUE THREAD

**Issue by mattcollier** [winfinit/aamvajs#14]
Hello, we really appreciate all the work that has gone into keeping this library up-to-date etc and we'd like to use it in a project.  The GPL 2+ license is not suitable for our use case.  Would you all consider a dual license GPL2+ and BSD?

**Comment by winfinit** [comment]
Hi there, I can change a license to anything you’d like, it was just some boilerplate file that was added to a project initially. Please submit a PR and I will merge it.

**Comment by winfinit** [comment]
thank you for your pull request, new version is merged and published to npm
